services:
  vue-app:
    image: node:latest
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./vueApp:/app
    # command: sh -c "cd vue-sample/ && npm run serve"
    ports:
      - "8090:8080"
