services:
  vue-app:
    image: ghcr.io/iichanize/sudoku_vue3:latest
    tty: true
    environment:
      - NODE_ENV=development
    # volumes:
    # - ./vueApp:/app
    command: sh -c "cd sudoku_vue3/vueApp/vue-sample/ && npm install && npm run serve"
    ports:
      - "8090:8080"
